# Generated by Django 6.0.7 on 2026-08-03 23:29

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('hora_entrega', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de entrega')),
                ('hora_devolucion', models.TimeField(default=datetime.time(17, 0), verbose_name='Hora de devolución')),
                ('lugar_entrega', models.CharField(default='Sucursal', max_length=120, verbose_name='Lugar de entrega')),
                ('lugar_devolucion', models.CharField(default='Sucursal', max_length=120, verbose_name='Lugar de devolución')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('precio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio total (RD$)')),
                ('deposito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Depósito (RD$)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio', '-creado_en'],
            },
        ),
    ]
