# Generated by Django 6.0.7 on 2026-08-04 01:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='combustible_devolucion',
            field=models.CharField(blank=True, choices=[('vacio', 'Vacío'), ('cuarto', '1/4'), ('medio', '1/2'), ('tres_cuartos', '3/4'), ('lleno', 'Lleno')], max_length=20, verbose_name='Combustible al devolver'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='combustible_entrega',
            field=models.CharField(blank=True, choices=[('vacio', 'Vacío'), ('cuarto', '1/4'), ('medio', '1/2'), ('tres_cuartos', '3/4'), ('lleno', 'Lleno')], max_length=20, verbose_name='Combustible al entregar'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='danos_devolucion',
            field=models.TextField(blank=True, verbose_name='Daños al devolver'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='danos_entrega',
            field=models.TextField(blank=True, verbose_name='Daños preexistentes'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='devolucion_registrada',
            field=models.BooleanField(default=False, verbose_name='Devolución registrada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='entrega_registrada',
            field=models.BooleanField(default=False, verbose_name='Entrega registrada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_devolucion',
            field=models.ImageField(blank=True, null=True, upload_to='reservas/devolucion/', verbose_name='Foto devolución'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='reservas/entrega/', verbose_name='Foto entrega'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='km_devolucion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km al devolver'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='km_entrega',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km al entregar'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas_devolucion',
            field=models.TextField(blank=True, verbose_name='Observaciones de devolución'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas_entrega',
            field=models.TextField(blank=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se registra automáticamente como pago al guardar la reserva.', max_digits=10, verbose_name='Depósito inicial (RD$)'),
        ),
    ]
