# Generated by Django 6.0.7 on 2026-08-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_combustible_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('panel', 'Panel'), ('web', 'Sitio web')], default='panel', max_length=10, verbose_name='Origen'),
        ),
    ]
