# Generated by Django 6.0.7 on 2026-08-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='requiere_contacto_web',
            field=models.BooleanField(default=False, help_text='Alerta en el panel hasta marcar como contactado.', verbose_name='Pendiente de contacto (web)'),
        ),
    ]
