# Generated by Django 6.0.7 on 2026-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_video_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='devolucion_registrada_en',
            field=models.DateTimeField(blank=True, help_text='Se usa para borrar el video de entrega unos días después de la devolución.', null=True, verbose_name='Devolución registrada el'),
        ),
    ]
