# Generated by Django 6.0.7 on 2026-08-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_devolucion_registrada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checklist_entrega',
            field=models.JSONField(blank=True, default=list, help_text='Claves de CHECKLIST_ITEMS marcadas como presentes al entregar el vehículo.', verbose_name='Checklist de entrega'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deducible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto que asume el cliente en caso de accidente o daño.', max_digits=10, null=True, verbose_name='Deducible (RD$)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='posible_retorno',
            field=models.DateField(blank=True, help_text='Solo si es distinto a la fecha de fin.', null=True, verbose_name='Posible retorno estimado'),
        ),
        migrations.CreateModel(
            name='ConductorAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Cédula')),
                ('pasaporte', models.CharField(blank=True, max_length=30, verbose_name='Pasaporte')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('nacionalidad', models.CharField(blank=True, max_length=60, verbose_name='Nacionalidad')),
                ('ocupacion', models.CharField(blank=True, max_length=80, verbose_name='Ocupación')),
                ('lugar_expedicion', models.CharField(blank=True, max_length=80, verbose_name='Expedido en')),
                ('licencia_numero', models.CharField(blank=True, max_length=30, verbose_name='Número de licencia')),
                ('licencia_vence', models.DateField(blank=True, null=True, verbose_name='Vencimiento de licencia')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_adicional', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Conductor adicional',
                'verbose_name_plural': 'Conductores adicionales',
            },
        ),
    ]
