# Generated by Django 6.0.7 on 2026-08-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_titulo', models.CharField(default='Alquiler de vehículos', max_length=160, verbose_name='Título del inicio')),
                ('home_subtitulo', models.CharField(blank=True, max_length=240, verbose_name='Subtítulo del inicio')),
                ('home_texto', models.TextField(blank=True, verbose_name='Texto del inicio')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('horario', models.CharField(blank=True, max_length=200, verbose_name='Horario de atención')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('reserva_auto_confirmar', models.BooleanField(default=False, help_text='Si está desactivado, las reservas web quedan pendientes hasta confirmarlas en el panel.', verbose_name='Confirmar reservas web automáticamente')),
                ('anticipacion_horas', models.PositiveSmallIntegerField(default=24, verbose_name='Anticipación mínima (horas)')),
                ('bloquear_mantenimiento', models.BooleanField(default=True, verbose_name='Ocultar vehículos en mantenimiento de la web')),
                ('mensaje_reserva_exito', models.TextField(blank=True, default='Gracias. Hemos recibido tu solicitud. Te contactaremos pronto para confirmar.', verbose_name='Mensaje tras reservar')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='PaginaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('en_menu', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en menú')),
            ],
            options={
                'verbose_name': 'Página informativa',
                'verbose_name_plural': 'Páginas informativas',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
