# Generated by Django 6.0.7 on 2026-08-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_logo_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='home_fondo_posicion',
            field=models.CharField(choices=[('left top', 'Arriba izquierda'), ('top', 'Arriba centro'), ('right top', 'Arriba derecha'), ('left', 'Centro izquierda'), ('center', 'Centro'), ('right', 'Centro derecha'), ('left bottom', 'Abajo izquierda'), ('bottom', 'Abajo centro'), ('right bottom', 'Abajo derecha')], default='center', help_text='Qué parte de la imagen se mantiene visible en pantallas angostas.', max_length=20, verbose_name='Posición de la foto'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='home_fondo_tamano',
            field=models.CharField(choices=[('cover', 'Cubrir — llena el espacio (puede recortar bordes)'), ('contain', 'Ajustar — se ve completa (puede dejar franjas)')], default='cover', max_length=10, verbose_name='Tamaño de la foto'),
        ),
    ]
