# Generated by Django 6.0.7 on 2026-08-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_configuracionsitio_home_fondo_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='home_subtitulo_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='Subtítulo del inicio (inglés)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='home_texto_en',
            field=models.TextField(blank=True, verbose_name='Texto del inicio (inglés)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='home_titulo_en',
            field=models.CharField(blank=True, help_text='Si lo dejas vacío, se usa el texto en español para los visitantes en inglés.', max_length=160, verbose_name='Título del inicio (inglés)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mensaje_reserva_exito_en',
            field=models.TextField(blank=True, verbose_name='Mensaje tras reservar (inglés)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='meta_descripcion_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta descripción (SEO inicio, inglés)'),
        ),
        migrations.AddField(
            model_name='paginainformativa',
            name='contenido_en',
            field=models.TextField(blank=True, help_text='Si lo dejas vacío, se usa el contenido en español para los visitantes en inglés.', verbose_name='Contenido (HTML, inglés)'),
        ),
        migrations.AddField(
            model_name='paginainformativa',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Si lo dejas vacío, se usa el título en español para los visitantes en inglés.', max_length=120, verbose_name='Título (inglés)'),
        ),
    ]
