# Generated by Django 6.0.7 on 2026-08-18 00:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_configuracionsitio_home_subtitulo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='entrega_aeropuertos',
            field=models.BooleanField(default=False, verbose_name='Entrega en aeropuertos de RD'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mostrar_resenas',
            field=models.BooleanField(default=False, verbose_name='Mostrar calificación de reseñas'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='resena_calificacion',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2, verbose_name='Calificación (de 5)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='resena_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de reseñas'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='servicio_24h',
            field=models.BooleanField(default=False, verbose_name='Atención 24 horas'),
        ),
    ]
