# Generated by Django 6.0.7 on 2026-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_config_actual_como_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='favicon',
            field=models.FileField(blank=True, help_text='PNG, ICO o WebP cuadrado. Recomendado: 32×32 o 192×192 px.', null=True, upload_to='sitio/favicon/', verbose_name='Icono del navegador (favicon)'),
        ),
    ]
