# Generated by Django 6.0.7 on 2026-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_favicon_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='mostrar_pie_copyright',
            field=models.BooleanField(default=True, help_text='Muestra u oculta la línea de copyright al final del sitio público.', verbose_name='Mostrar derechos de autor en el pie'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='pie_copyright_texto',
            field=models.CharField(blank=True, help_text='Ej: © 2026 Mi Negocio. Todos los derechos reservados. Si está vacío se usa el nombre de la empresa.', max_length=240, verbose_name='Texto de derechos de autor'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='pie_copyright_url',
            field=models.URLField(blank=True, help_text='Si lo completas, el texto del pie será un enlace clickeable.', verbose_name='Enlace del pie (opcional)'),
        ),
    ]
