# Generated by Django 6.0.7 on 2026-09-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_home_destacados_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='email_notificaciones',
            field=models.EmailField(blank=True, default='', help_text='El sistema enviará un email a esta dirección cada vez que llegue una reserva nueva.', max_length=254, verbose_name='Email para notificaciones de reservas'),
        ),
    ]
