# Generated by Django 6.0.7 on 2026-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_configuracionsitio_email_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email_notificaciones',
            field=models.TextField(blank=True, default='', help_text='Puedes agregar varios correos separados por comas. Ej: roberto@gmail.com, eugenio@gmail.com', verbose_name='Email para notificaciones de reservas'),
        ),
    ]
