# Generated by Django 6.0.7 on 2026-08-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('calendario', 'Calendario'), ('vehiculos', 'Vehículos'), ('mantenimiento', 'Mantenimiento'), ('reservas', 'Reservas'), ('clientes', 'Clientes'), ('pagos', 'Pagos'), ('reportes', 'Reportes'), ('configuracion', 'Configuración')], max_length=30, unique=True, verbose_name='Módulo')),
                ('permitido', models.BooleanField(default=True, verbose_name='Permitido para empleados')),
            ],
            options={
                'verbose_name': 'Acceso de empleado',
                'verbose_name_plural': 'Accesos de empleados',
                'ordering': ['modulo'],
            },
        ),
    ]
