# Generated by Django 6.0.7 on 2026-08-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesomodulo',
            options={'ordering': ['modulo'], 'permissions': [('modulo_dashboard', 'Acceder al Dashboard'), ('modulo_calendario', 'Acceder al Calendario'), ('modulo_vehiculos', 'Acceder a Vehículos'), ('modulo_mantenimiento', 'Acceder a Mantenimiento'), ('modulo_reservas', 'Acceder a Reservas'), ('modulo_clientes', 'Acceder a Clientes'), ('modulo_pagos', 'Acceder a Pagos'), ('modulo_reportes', 'Acceder a Reportes'), ('modulo_configuracion', 'Acceder a Configuración')], 'verbose_name': 'Acceso de empleado', 'verbose_name_plural': 'Accesos de empleados'},
        ),
    ]
