# Generated by Django 6.0.7 on 2026-08-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accesomodulo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesomodulo',
            options={'ordering': ['modulo'], 'permissions': [('modulo_dashboard', 'Acceder al Dashboard'), ('modulo_calendario', 'Acceder al Calendario'), ('modulo_vehiculos', 'Acceder a Vehículos'), ('modulo_mantenimiento', 'Acceder a Mantenimiento'), ('modulo_reservas', 'Acceder a Reservas'), ('modulo_clientes', 'Acceder a Clientes'), ('modulo_pagos', 'Acceder a Pagos'), ('modulo_reportes', 'Acceder a Reportes'), ('modulo_configuracion', 'Acceder a Configuración'), ('modulo_sitio_web', 'Acceder al Sitio web')], 'verbose_name': 'Acceso de empleado', 'verbose_name_plural': 'Accesos de empleados'},
        ),
        migrations.AlterField(
            model_name='accesomodulo',
            name='modulo',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('calendario', 'Calendario'), ('vehiculos', 'Vehículos'), ('mantenimiento', 'Mantenimiento'), ('reservas', 'Reservas'), ('clientes', 'Clientes'), ('pagos', 'Pagos'), ('reportes', 'Reportes'), ('sitio_web', 'Sitio web'), ('configuracion', 'Configuración')], max_length=30, unique=True, verbose_name='Módulo'),
        ),
    ]
