# Generated by Django 6.0.7 on 2026-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lugar_expedicion',
            field=models.CharField(blank=True, help_text='Lugar de expedición de la cédula o pasaporte.', max_length=80, verbose_name='Expedido en'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pasaporte',
            field=models.CharField(blank=True, help_text='Para clientes extranjeros, si aplica.', max_length=30, verbose_name='Pasaporte'),
        ),
    ]
