# Generated by Django 6.0.7 on 2026-08-16 22:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0005_vehiculo_fecha_compra_vehiculo_precio_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('puesto', models.CharField(blank=True, max_length=80, verbose_name='Puesto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('salario_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Referencial. Los pagos reales se registran en Nómina.', max_digits=10, verbose_name='Salario base (RD$)')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120, verbose_name='Concepto')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('seguro', 'Seguro'), ('publicidad', 'Publicidad'), ('oficina', 'Oficina / administrativo'), ('impuestos', 'Impuestos'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (RD$)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Si el gasto es específico de un vehículo, selecciónalo para incluirlo en su rentabilidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='vehiculos.vehiculo', verbose_name='Vehículo (opcional)')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('salario', 'Salario'), ('bono', 'Bono'), ('comision', 'Comisión'), ('otro', 'Otro')], default='salario', max_length=20, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (RD$)')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Método')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_nomina', to='finanzas.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Pago de nómina',
                'verbose_name_plural': 'Pagos de nómina',
                'ordering': ['-fecha_pago', '-creado_en'],
            },
        ),
    ]
