# Generated by Django 6.0.7 on 2026-08-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Deja Vu Rent Car', max_length=120, verbose_name='Nombre comercial')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('rnc', models.CharField(blank=True, max_length=20, verbose_name='RNC')),
                ('notas_contrato', models.TextField(blank=True, verbose_name='Cláusulas del contrato')),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
            },
        ),
    ]
