# Generated by Django 6.0.7 on 2026-08-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='ciudad',
            field=models.CharField(default='Santiago', help_text='Se usa en el SEO del sitio para posicionar en búsquedas de esta ciudad.', max_length=80, verbose_name='Ciudad'),
        ),
    ]
