# Generated by Django 6.0.7 on 2026-08-21 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_datos_reales_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='bloqueo_inactividad_horas',
            field=models.PositiveSmallIntegerField(default=10, help_text='Cierra la sesión del panel si no hay actividad durante este tiempo (1 a 168 horas).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Bloqueo por inactividad (horas)'),
        ),
    ]
