# Generated by Django 6.0.7 on 2026-08-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (RD$)')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('parcial', 'Pago parcial'), ('total', 'Pago total'), ('reembolso', 'Reembolso')], default='parcial', max_length=20, verbose_name='Tipo')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método')),
                ('referencia', models.CharField(blank=True, max_length=60, verbose_name='Referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
