# Generated by Django 6.0.7 on 2026-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tarjeta_autorizacion',
            field=models.CharField(blank=True, max_length=40, verbose_name='No. de autorización'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarjeta_tipo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarjeta_ultimos4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarjeta_vencimiento',
            field=models.CharField(blank=True, help_text='MM/AA', max_length=10, verbose_name='Vencimiento de tarjeta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo (RD$)'), ('dolar', 'Dólar (US$)'), ('euro', 'Euro (€)'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método'),
        ),
    ]
