# Generated by Django 6.0.7 on 2026-08-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('categoria', models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('van', 'Van'), ('lujo', 'Lujo')], default='sedan', max_length=20, verbose_name='Categoría')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa diaria (RD$)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20, verbose_name='Estado')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('kilometraje', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto')),
                ('seguro_vence', models.DateField(blank=True, null=True, verbose_name='Vencimiento del seguro')),
                ('prox_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
