# Generated by Django 6.0.7 on 2026-08-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion_web',
            field=models.TextField(blank=True, verbose_name='Descripción (web)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='destacado_web',
            field=models.BooleanField(default=False, verbose_name='Destacado en inicio'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='orden_web',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden en web'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('cvt', 'CVT')], default='automatico', max_length=20, verbose_name='Transmisión'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='visible_en_web',
            field=models.BooleanField(default=False, verbose_name='Visible en sitio web'),
        ),
    ]
