# Generated by Django 6.0.7 on 2026-08-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_descripcion_web_vehiculo_destacado_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/galeria/', verbose_name='Imagen')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Foto de vehículo',
                'verbose_name_plural': 'Fotos de vehículo',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('vehiculo', 'orden'), name='vehiculo_foto_orden_unico'), models.CheckConstraint(condition=models.Q(('orden__gte', 1), ('orden__lte', 3)), name='vehiculo_foto_orden_1_3')],
            },
        ),
    ]
