# Generated by Django 6.0.7 on 2026-08-16 22:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de compra'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lo que costó adquirir el vehículo. Se usa para calcular la rentabilidad.', max_digits=10, verbose_name='Precio de compra (RD$)'),
        ),
    ]
