# Generated by Django 6.0.7 on 2026-08-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_fecha_compra_vehiculo_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Alternativa a subir un archivo: pega el link de una imagen ya alojada en otro sitio.', max_length=500, verbose_name='Enlace de la foto'),
        ),
    ]
