# Generated by Django 6.0.7 on 2026-08-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculo_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion_web_en',
            field=models.TextField(blank=True, help_text='Si la dejas vacía, se usa la descripción en español para los visitantes en inglés.', verbose_name='Descripción (web, inglés)'),
        ),
    ]
