# Generated by Django 6.0.7 on 2026-08-04 00:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('revision', 'Revisión general')], default='revision', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo (RD$)')),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('proximo_servicio', models.DateField(blank=True, null=True, verbose_name='Próximo servicio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
